ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: placeholder.local   # Giá trị tạm, sẽ override trong ingress.yaml
      paths:
        - path: /
          pathType: Prefix
