global:
  dockerhubRepo: "hykura/"
  namespace: "dev"
  imagePullPolicy: "Always"

services:
  config-server:
    enabled: true
    image:
      repository: spring-petclinic-config-server
      tag: latest
    service:
      type: NodePort
      port: 8888
      nodePort: 30001
    readinessProbe:
      httpGet:
        path: /
        port: 8888
      initialDelaySeconds: 30
      periodSeconds: 10

  discovery-server:
    enabled: true
    image:
      repository: spring-petclinic-discovery-server
      tag: latest
    service:
      type: NodePort
      port: 8761
      nodePort: 30002
    readinessProbe:
      httpGet:
        path: /
        port: 8761
      initialDelaySeconds: 30
      periodSeconds: 10

  customers-service:
    enabled: true
    image:
      repository: spring-petclinic-customers-service
      tag: latest
    service:
      type: NodePort
      port: 8081
      nodePort: 30003

  visits-service:
    enabled: true
    image:
      repository: spring-petclinic-visits-service
      tag: latest
    service:
      type: NodePort
      port: 8082
      nodePort: 30004

  vets-service:
    enabled: true
    image:
      repository: spring-petclinic-vets-service
      tag: latest
    service:
      type: NodePort
      port: 8083
      nodePort: 30005

  api-gateway:
    enabled: true
    image:
      repository: spring-petclinic-api-gateway
      tag: latest
    service:
      type: NodePort
      port: 8080
      nodePort: 30006

  admin-server:
    enabled: true
    image:
      repository: spring-petclinic-admin-server
      tag: latest
    service:
      type: NodePort
      port: 9090
      nodePort: 30007