namespace: dev
imagePullPolicy: IfNotPresent

docker:
  repository: phanphuc269

ingress:
  name: spring-petclinic-ingress
  host: petclinic.phanphuc.id.vn
  httpNodePort: 32080
  httpsNodePort: 32443
  userServiceName: api-gateway
  userServicePort: 8080
  adminServiceName: admin-server
  adminServicePort: 9090
  eurekaServiceName: discovery-server
  eurekaServicePort: 8761

configServerEnv: &configServerEnv
  name: CONFIG_SERVER_URL
  value: http://config-server:8888

dependOnEureka: &dependOnEureka
  name: discovery-server
  port: 8761

services:
  config-server:
    enable: true
    ports:
      port: 8888
      targetPort: 8888
    image:
      name: spring-petclinic-config-server

  discovery-server:
    enable: true
    ports:
      port: 8761
      targetPort: 8761
    image:
      name: spring-petclinic-discovery-server
    env: 
      - *configServerEnv
    dependOn: 
      name: config-server
      port: 8888

  admin-server:
    enable: true
    ports:
      port: 9090
      targetPort: 9090
    image:
      name: spring-petclinic-admin-server
    env: 
      - *configServerEnv
    dependOn: *dependOnEureka

  customers-service:
    enable: true
    ports:
      port: 8081
      targetPort: 8081
    image:
      name: spring-petclinic-customers-service
    env: 
      - *configServerEnv
    dependOn: *dependOnEureka

  visits-service:
    enable: true
    ports:
      port: 8082
      targetPort: 8082
    image:
      name: spring-petclinic-visits-service
    env: 
      - *configServerEnv
    dependOn: *dependOnEureka

  vets-service:
    enable: true
    ports:
      port: 8083
      targetPort: 8083
    image:
      name: spring-petclinic-vets-service
    env: 
      - *configServerEnv
    dependOn: *dependOnEureka

  api-gateway:
    enable: true
    ports:
      port: 8080
      targetPort: 8080
    image:
      name: spring-petclinic-api-gateway
    env: 
      - *configServerEnv
    dependOn: *dependOnEureka
