# values.yaml
global:
  namespace: dev # Default namespace, overridden by Helm --namespace
  dockerhubRepo: phanphuc269/ # DockerHub repository
  imagePullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: petclinic
      paths:
        - path: /
          pathType: Prefix

services:
  vets-service:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-vets-service
      tag: latest
    service:
      type: ClusterIP
      port: 8080
    resources: {}
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

  customers-service:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-customers-service
      tag: latest
    service:
      type: ClusterIP
      port: 8080
    resources: {}
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

  visits-service:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-visits-service
      tag: latest
    service:
      type: ClusterIP
      port: 8080
    resources: {}
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

  api-gateway:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-api-gateway
      tag: latest
    service:
      type: ClusterIP # Changed from NodePort to work with Ingress
      port: 80
    resources: {}
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10

  config-server:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-config-server
      tag: latest
    service:
      type: ClusterIP
      port: 8888
    resources: {}

  discovery-server:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-discovery-server
      tag: latest
    service:
      type: ClusterIP
      port: 8761
    resources: {}

  admin-server:
    enabled: true
    replicas: 1
    image:
      repository: spring-petclinic-admin-server
      tag: latest
    service:
      type: ClusterIP
      port: 9100
    resources: {}