apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-clinic-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/phanphuc269/helm-petclinic.git' 
    targetRevision: HEAD                
    path: .        
    helm:
      valueFiles:
        - values.yaml                   
        - environments/values-staging.yaml  

  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: staging                         

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true