apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.11
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - grafana.phanphuc.id.vn
          ingressClassName: nginx
          path: /
          pathType: Prefix
        service:
          type: NodePort
          nodePort: 32000
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.monitoring:3100
                isDefault: false
                editable: true
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server.monitoring:80
                isDefault: true
                editable: true
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                updateIntervalSeconds: 10
                options:
                  path: /var/lib/grafana/dashboards

        dashboards:
          default:
            petclinic-dashboard:
              file: applications/dashboards/grafana-petclinic-dashboard.json
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true