apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 9.2.7
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - grafana.phanphuc.id.vn
          ingressClassName: nginx
          path: /
          pathType: Prefix
        service:
          type: NodePort
          nodePort: 32000
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.monitoring:3100
                isDefault: false
                editable: true
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server.monitoring:80
                isDefault: true
                editable: true
              - name: Zipkin
                type: zipkin
                access: proxy
                url: http://zipkin.monitoring:9411
                isDefault: false
                editable: true
                uid: aepemvvhucw74f
                jsonData:
                  tracesToLogsV2:
                    customQuery: true
                    query: '{app=~".+"}  |= "${__trace.traceId}"'
                    datasource: Loki
                    spanEndTimeShift: 1h
                    spanStartTimeShift: -1h
                    tags:
                      - key: app
                        value: app
                  tracesToMetrics:
                    datasource: Prometheus
                    queries:
                      - name: Metrics
                        query: http_server_requests_seconds_count
                    spanEndTimeShift: 1h
                    spanStartTimeShift: -1h
                    tags:
                      - key: app
                        value: app
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default

        dashboards:
          default:
            petclinic-traffic-logs:
              json: |
                {
                  "title": "Petclinic Traffic & Logs",
                  "uid": "petclinic-traffic-logs",
                  "schemaVersion": 16,
                  "version": 1,
                  "panels": [
                    {
                      "type": "stat",
                      "title": "HTTP Request Count",
                      "datasource": "Prometheus",
                      "targets": [
                        {
                          "expr": "sum(http_server_requests_seconds_count)  OR vector(0)",
                          "legendFormat": "Tổng request"
                        },
                        {
                          "expr": "sum(http_server_requests_seconds_count{status=~\"2..\"})  OR vector(0)",
                          "legendFormat": "Request 2xx"
                        },
                        {
                          "expr": "sum(http_server_requests_seconds_count{status=~\"5..\"})  OR vector(0)",
                          "legendFormat": "Request 5xx"
                        }
                      ],
                      "gridPos": {
                        "h": 8,
                        "w": 24,
                        "x": 0,
                        "y": 0
                      }
                    },
                    {
                      "type": "logs",
                      "title": "Application Logs",
                      "datasource": "Loki",
                      "targets": [
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "editorMode": "code",
                          "expr": "{app=\"api-gateway\"} |= ``",
                          "queryType": "range",
                          "refId": "A"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "editorMode": "builder",
                          "expr": "{app=\"admin-server\"} |= ``",
                          "hide": false,
                          "queryType": "range",
                          "refId": "B"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "editorMode": "builder",
                          "expr": "{app=\"customers-service\"} |= ``",
                          "hide": false,
                          "queryType": "range",
                          "refId": "C"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "editorMode": "builder",
                          "expr": "{app=\"vets-service\"} |= ``",
                          "hide": false,
                          "queryType": "range",
                          "refId": "D"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "editorMode": "builder",
                          "expr": "{app=\"visits-service\"} |= ``",
                          "hide": false,
                          "queryType": "range",
                          "refId": "E"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "editorMode": "builder",
                          "expr": "{app=\"discovery-server\"} |= ``",
                          "hide": false,
                          "queryType": "range",
                          "refId": "F"
                        }
                      ],
                      "gridPos": {
                        "h": 10,
                        "w": 24,
                        "x": 0,
                        "y": 8
                      }
                    }
                  ]
                }

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true