apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    role: alert-rules
    app: prometheus
data:
  alerting_rules.yaml: |
    groups:
      - name: request_error_alerts
        interval: 30s
        rules:
          - alert: HighRequestErrorRate
            expr: |
              sum by (job) (
                rate(http_server_requests_seconds_count{status=~"5.."}[30s])
              ) > 10
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "Tăng đột biến số lượng request lỗi ở job {{ $labels.job }}"
              description: "Có hơn 10 request lỗi (5xx) trong 30 giây ở {{ $labels.job }}"
