apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.2.0
    helm:
      values: |
        grafana:
          enabled: false  # ❌ Tắt Grafana

        alertmanager:
          enabled: true   # ✅ Bật Alertmanager
          alertmanagerSpec:
            replicas: 1
          ingress:
            enabled: true
            hosts:
              - alertmanager.phanphuc.id.vn
            ingressClassName: nginx

        prometheus:
          enabled: true
          service:
            type: NodePort
            nodePort: 32001
            port: 9090
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false

        additionalPrometheusRulesMap:
          high_request_errors:
            groups:
              - name: request.error.rules
                rules:
                  - alert: HighErrorRate
                    expr: increase(http_requests_total{status=~"5.."}[30s]) > 10
                    for: 0s
                    labels:
                      severity: warning
                    annotations:
                      summary: "High error rate detected"
                      description: "More than 10 error requests in 30 seconds on {{ $labels.instance }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
