namespace: dev

services:
  config-server:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest

  admin-server:
    image:
      tag: latest

  customers-service:
    image:
      tag: latest

  visits-service:
    image:
      tag: latest

  vets-service:
    image:
      tag: latest

  genai-service:
    image:
      tag: latest

  api-gateway:
    image:
      tag: 56ff5e8
