namespace: dev

services:
  config-server:
    enable: true
    ports:
      port: 8888
      targetPort: 8888
    image:
      tag: 339b054

  discovery-server:
    enable: true
    ports:
      port: 8761
      targetPort: 8761
    image:
      tag: 339b054

  admin-server:
    enable: true
    ports:
      port: 9090
      targetPort: 9090
    image:
      tag: 339b054


  customers-service:
    enable: true
    ports:
      port: 8081
      targetPort: 8081
    image:
      tag: 339b054

  visits-service:
    enable: true
    ports:
      port: 8082
      targetPort: 8082
    image:
      tag: 339b054

  vets-service:
    enable: true
    ports:
      port: 8083
      targetPort: 8083
    image:
      tag: 339b054

  api-gateway:
    enable: true
    ports:
      port: 8080
      targetPort: 8080
    image:
      tag: 339b054
