{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      {{- $configPort := index (index (index $.Values.services "config-server") "service") "port" }}
      {{- $discoveryPort := index (index (index $.Values.services "discovery-server") "service") "port" }}

      {{- if eq $name "discovery-server" }}
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ["sh", "-c", "until wget -q --spider http://config-server:{{ $configPort }}/; do echo waiting for config server; sleep 2; done;"]
      {{- end }}

      {{- if and (ne $name "discovery-server") (ne $name "config-server") }}
      initContainers:
      - name: wait-for-discovery-server
        image: busybox
        command: ["sh", "-c", "until wget -q --spider http://discovery-server:{{ $discoveryPort }}/actuator/health; do echo waiting for discovery server; sleep 2; done;"]
      {{- end }}

      containers:
      - name: {{ $name }}
        image: "{{ $.Values.global.dockerhubRepo }}{{ $service.image.repository }}:{{ $service.image.tag }}"
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ $service.service.port }}
        {{- if ne $name "config-server" }}
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:{{ $configPort }}
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:{{ $discoveryPort }}/eureka/
        {{- end }}
        resources:
          {{- toYaml $service.resources | nindent 12 }}
        {{- if $service.readinessProbe }}
        readinessProbe:
          {{- toYaml $service.readinessProbe | nindent 12 }}
        {{- end }}
---
{{- end }}
{{- end }}
