{{- range $name, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      {{- if $service.dependOn }}
      initContainers:
        - name: init-container-for-{{ $name }}
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - >
              until curl -I http://{{ $service.dependOn.name }}:{{ $service.dependOn.port }};
              do echo "waiting for {{ $service.dependOn.name }}..."; sleep 5;
              done
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ $service.dockerRepository | default $.Values.docker.repository }}/{{ $service.image.name }}:{{ $service.image.tag | default "latest" }}"
          imagePullPolicy: "{{ $.Values.imagePullPolicy | default "Always"}}"
          ports:
            - containerPort: {{ $service.ports.targetPort | default 0 }}
          env:
            {{- with $service.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ $name }}
            {{- if eq $name "admin-server" }}
            - name: SPRING_BOOT_ADMIN_PUBLIC_URL
              value: "http://admin.{{ $.Values.namespace }}-{{ $.Values.ingress.host }}:{{ $.Values.ingress.httpNodePort }}/"
            {{- end }}
---
{{- end }}