apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-petclinic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ regexReplaceAll "^petclinic-" .Release.Namespace "" }}.petclinic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
          - path: /eureka
            pathType: Prefix
            backend:
              service:
                name: discovery-server
                port:
                  number: 8761
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-server
                port:
                  number: 9100