{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  type: {{ $service.service.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: {{ $service.service.port }}
      {{- if eq $service.service.type "NodePort" }}
      nodePort: {{ $service.service.nodePort }}
      {{- end }}
---
{{- end }}
{{- end }} 